Repository SumoLogic/terraform-provider-sumologic, pull requests merged in 2020-05, with the labels that each got.

#8 Error checking aggregate types
  CHANGELOG.md
  sumologic/data_source_sumologic_collector.go
  sumologic/resource_sumologic_cloudsyslog_source.go
  sumologic/resource_sumologic_collector.go
  sumologic/resource_sumologic_connection.go
  sumologic/resource_sumologic_http_source.go
  sumologic/resource_sumologic_polling_source.go
  sumologic/resource_sumologic_role.go
  sumologic/resource_sumologic_user.go
  sumologic/sumologic_client.go
  sumologic/sumologic_sources.go
Labels: size/M

#11 forcing new resource on update, and fix json equivalency code
  CHANGELOG.md
  go.sum
  sumologic/resource_sumologic_content.go
Labels: bug, size/M

#12 updates to readme
  README.md
Labels: documentation, size/S

#14 Don't use default value for retention_period in test
  sumologic/resource_sumologic_partition_test.go
Labels: size/XS

#13 Update README.md
  README.md
Labels: size/XS

#15 Create CODEOWNERS
  .github/CODEOWNERS
Labels: size/XS

#9 Add support for contentType
  sumologic/resource_sumologic_http_source_test.go
  sumologic/sumologic_sources.go
Labels: size/S

#18 SUMO-0: add tkao1000 to code owners
  .github/CODEOWNERS
Labels: size/XS
