Repository SumoLogic/terraform-provider-sumologic, pull requests merged in 2020-07, with the labels that each got.

#41 fix typo in polling source
  website/docs/r/polling_source.html.markdown
Labels: documentation, size/XS

#44 fixing bug for detecting changes on polling source
  sumologic/resource_sumologic_polling_source.go
Labels: size/XS

#45 use the official function for json diff
  sumologic/resource_sumologic_content.go
Labels: size/XS

#50 add reference to common source properties in all sources
  website/docs/r/cloudsyslog_source.html.markdown
  website/docs/r/collector.html.markdown
  website/docs/r/http_source.html.markdown
  website/docs/r/polling_source.html.markdown
Labels: documentation, size/XS

#51 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#47 content/folder: use resource.StateChangeConf to improve job polling
  sumologic/resource_sumologic_content.go
  sumologic/resource_sumologic_content_test.go
  sumologic/resource_sumologic_folder.go
  sumologic/sumologic_content.go
  sumologic/sumologic_folder.go
  website/docs/r/content.html.markdown
  website/docs/r/folder.html.markdown
Labels: documentation, size/L
