Repository SumoLogic/terraform-provider-sumologic, pull requests merged in 2020-06, with the labels that each got.

#20 fix bug with redirect endpoint for prod
  sumologic/provider.go
Labels: size/XS

#21 update changelog v2.0.3
  CHANGELOG.md
Labels: size/XS

#23 Fix usage example for sumologic_content resource
  CHANGELOG.md
  website/docs/r/content.html.markdown
Labels: documentation, size/XS

#25 SUMO-0: Rename scheduled view file
  sumologic/sumologic_scheduled_view.go
Labels: size/XS

#29 remove users from role documentation
  website/docs/r/role.html.markdown
Labels: documentation, size/XS

#31 Ssain import docs typos 1
  website/docs/r/role.html.markdown
  website/docs/r/user.html.markdown
Labels: documentation, size/XS

#34 add CW metrics in Changelog
  CHANGELOG.md
Labels: size/XS

#35 add docs for CW metrics
  website/docs/r/polling_source.html.markdown
Labels: documentation, size/S

#37 Update polling_source.html.markdown
  website/docs/r/polling_source.html.markdown
Labels: documentation, size/XS
